# Generated by Django 3.2.9 on 2021-11-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtActivations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=120)),
                ('login', models.CharField(max_length=64)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('date_creation', models.CharField(max_length=32)),
                ('date_expiration', models.CharField(max_length=32)),
                ('resend_count', models.SmallIntegerField(blank=True, null=True)),
                ('resend_next', models.CharField(blank=True, max_length=32, null=True)),
                ('attempts', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'et_activations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('message', models.TextField()),
                ('lang', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'et_alerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtAuthTokens',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=280)),
                ('login', models.CharField(max_length=32)),
                ('ip_address', models.CharField(max_length=32)),
                ('user_agent', models.CharField(max_length=280)),
                ('browser', models.CharField(blank=True, max_length=32, null=True)),
                ('date_creation', models.CharField(max_length=32)),
                ('date_expiration', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'et_auth_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64)),
                ('balance', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=12)),
                ('alias', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('date_update', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'et_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'et_countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('alias', models.CharField(max_length=12)),
                ('symbol', models.CharField(blank=True, max_length=12, null=True)),
                ('type', models.SmallIntegerField(blank=True, null=True)),
                ('iso_code', models.IntegerField(blank=True, null=True)),
                ('decimal_number_system', models.SmallIntegerField(blank=True, null=True)),
                ('decimal_separator', models.CharField(blank=True, max_length=8, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'et_currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtFaq',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.SmallIntegerField()),
                ('question', models.CharField(max_length=260)),
                ('answer', models.TextField()),
                ('date_creation', models.CharField(blank=True, max_length=32, null=True)),
                ('date_update', models.CharField(blank=True, max_length=32, null=True)),
                ('sort', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'et_faq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtFinanceRates',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_f', models.CharField(blank=True, max_length=12, null=True)),
                ('currency_t', models.CharField(blank=True, max_length=12, null=True)),
                ('rate_buy', models.CharField(blank=True, max_length=32, null=True)),
                ('rate_sell', models.CharField(blank=True, max_length=32, null=True)),
                ('rate_exchange', models.CharField(blank=True, max_length=32, null=True)),
                ('date_update', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'et_finance_rates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtFinanceRequisites',
            fields=[
                ('finance_requisite_id', models.AutoField(primary_key=True, serialize=False)),
                ('finance_id', models.IntegerField(blank=True, null=True)),
                ('alias', models.CharField(blank=True, max_length=120, null=True)),
                ('username', models.CharField(max_length=280)),
                ('password', models.CharField(max_length=280)),
                ('merchant_id', models.CharField(max_length=280)),
                ('api_key', models.CharField(max_length=320)),
                ('private_key', models.TextField()),
                ('secret_key', models.CharField(max_length=320)),
            ],
            options={
                'db_table': 'et_finance_requisites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtFinances',
            fields=[
                ('finance_id', models.AutoField(primary_key=True, serialize=False)),
                ('finance_type', models.SmallIntegerField(blank=True, null=True)),
                ('direction', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=280)),
                ('alias', models.CharField(max_length=280)),
                ('logo', models.CharField(blank=True, max_length=16, null=True)),
                ('currency', models.CharField(max_length=32)),
                ('date_creation', models.CharField(max_length=32)),
                ('date_update', models.CharField(max_length=32)),
                ('balance', models.CharField(blank=True, max_length=32, null=True)),
                ('min_qty', models.CharField(max_length=32)),
                ('max_qty', models.CharField(max_length=32)),
                ('step_size', models.CharField(max_length=32)),
                ('commission', models.CharField(blank=True, max_length=12, null=True)),
                ('addination_fees', models.CharField(blank=True, max_length=12, null=True)),
                ('cashout_fees', models.CharField(blank=True, max_length=12, null=True)),
                ('cashout_status', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'et_finances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtForgotten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=120)),
                ('login', models.CharField(max_length=120)),
                ('date_creation', models.CharField(max_length=32)),
                ('resend_next', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'et_forgotten',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('iso', models.CharField(max_length=280)),
                ('alias', models.CharField(max_length=280)),
                ('align', models.CharField(max_length=280)),
                ('sort', models.IntegerField()),
            ],
            options={
                'db_table': 'et_lang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtNotifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('date_creation', models.CharField(max_length=32)),
                ('date_update', models.CharField(max_length=32)),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'et_notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtOperations',
            fields=[
                ('operation_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.SmallIntegerField()),
                ('guid', models.CharField(blank=True, max_length=120, null=True)),
                ('login', models.CharField(max_length=32)),
                ('method', models.CharField(blank=True, max_length=32, null=True)),
                ('currency', models.CharField(blank=True, max_length=12, null=True)),
                ('sum', models.CharField(max_length=32)),
                ('credit', models.CharField(blank=True, max_length=32, null=True)),
                ('debit', models.CharField(blank=True, max_length=32, null=True)),
                ('commission', models.CharField(blank=True, max_length=32, null=True)),
                ('rate', models.CharField(blank=True, max_length=12, null=True)),
                ('date_creation', models.CharField(max_length=32)),
                ('date_update', models.CharField(blank=True, max_length=32, null=True)),
                ('ip_address', models.CharField(max_length=32)),
                ('memo', models.TextField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'et_operations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('alias', models.CharField(max_length=240)),
                ('user_access', models.CharField(max_length=32)),
                ('user_group', models.CharField(max_length=32)),
                ('default_redirect', models.CharField(max_length=32)),
                ('access_ip', models.CharField(max_length=320)),
                ('date_creation', models.CharField(max_length=32)),
                ('date_update', models.CharField(max_length=32)),
                ('lang', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'et_pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=280)),
                ('name', models.CharField(max_length=280)),
                ('alias', models.CharField(max_length=280)),
                ('value', models.CharField(max_length=280)),
                ('sort', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'et_parameters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32)),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('date_creation', models.CharField(max_length=32)),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'et_reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=120)),
                ('login', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=120)),
                ('firstname', models.CharField(blank=True, max_length=32, null=True)),
                ('lastname', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('photo', models.CharField(blank=True, max_length=32, null=True)),
                ('date_creation', models.CharField(max_length=32)),
                ('date_update', models.CharField(blank=True, max_length=32, null=True)),
                ('user_group', models.CharField(max_length=16)),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'et_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtUsersAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64)),
                ('action', models.SmallIntegerField()),
                ('date_creation', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('ip_address', models.CharField(max_length=32)),
                ('user_browser', models.CharField(max_length=32)),
                ('user_agent', models.CharField(max_length=320)),
                ('screen_resolution', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'et_users_action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtUsersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('alias', models.CharField(max_length=64)),
                ('redirect', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'et_users_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtUsersOnline',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=120)),
                ('login', models.CharField(blank=True, max_length=32, null=True)),
                ('date_update', models.CharField(blank=True, max_length=32, null=True)),
                ('date_expire', models.CharField(max_length=32)),
                ('user_agent', models.CharField(max_length=320)),
                ('ip_address', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'et_users_online',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150, verbose_name='Токен продавца')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('sell', models.IntegerField(blank=True, verbose_name='ID продаваемой крипты')),
                ('buy', models.IntegerField(blank=True, verbose_name='ID покупаемой крипты')),
                ('sell_quantity', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Сумма продаваемой крипты')),
                ('buy_quantity', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Сумма покупаемой крипты')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('participant', models.CharField(blank=True, max_length=150, verbose_name='Токен покупателя')),
                ('type', models.CharField(choices=[('1', 'Крипта'), ('2', 'Карта'), ('3', 'Наличка')], max_length=30, verbose_name='Тип сделки')),
            ],
            options={
                'db_table': 'et_trade',
            },
        ),
    ]
