# Generated by Django 3.2.9 on 2021-11-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('sell', models.IntegerField()),
                ('buy', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.IntegerField()),
            ],
        ),
    ]
