# Generated by Django 3.2.9 on 2021-11-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='owner',
            field=models.CharField(max_length=150, verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='participant',
            field=models.CharField(blank=True, max_length=150, verbose_name='Email покупателя'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='type',
            field=models.CharField(choices=[(1, 'Крипта'), (2, 'Карта'), (3, 'Наличка')], max_length=30, verbose_name='Тип сделки'),
        ),
    ]
