# Generated by Django 3.2.9 on 2021-11-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='type',
            field=models.CharField(choices=[('1', 'Крипта'), ('2', 'Карта'), ('3', 'Наличка')], default=1, max_length=30, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='buy',
            field=models.IntegerField(blank=True, verbose_name='ID покупаемой крипты'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='owner',
            field=models.CharField(max_length=150, verbose_name='Токен продавца'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='participant',
            field=models.CharField(blank=True, max_length=150, verbose_name='Токен покупателья'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell',
            field=models.IntegerField(blank=True, verbose_name='ID продаваемой крипты'),
        ),
    ]
