# Generated by Django 3.2.9 on 2021-11-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20211108_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Тип сделки'),
        ),
    ]
