# Generated by Django 3.2.9 on 2021-11-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20211103_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='type',
            field=models.CharField(choices=[('1', 'Крипта'), ('2', 'Карта'), ('3', 'Наличка')], max_length=30, verbose_name='Тип сделки'),
        ),
    ]
