# Generated by Django 3.2.9 on 2021-11-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_trade_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='buy',
            new_name='buy_currency',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='sell',
            new_name='sell_currency',
        ),
    ]
