# Generated by Django 3.2.9 on 2021-11-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20211103_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='quantity',
        ),
        migrations.AddField(
            model_name='trade',
            name='buy_quantity',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=19, verbose_name='Сумма покупаемой крипты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='sell_quantity',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=19, verbose_name='Сумма продаваемой крипты'),
            preserve_default=False,
        ),
    ]
