# Generated by Django 3.2.9 on 2021-11-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20211108_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Выплачено'),
        ),
    ]
