# Generated by Django 3.2.9 on 2021-11-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_trade_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус сделки'),
        ),
    ]
