# Generated by Django 3.2.9 on 2021-11-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20211109_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradecash',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Статус сделки'),
        ),
        migrations.AlterField(
            model_name='tradecript',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Статус сделки'),
        ),
    ]
