# Generated by Django 3.2.9 on 2021-11-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_auto_20211109_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150, verbose_name='Email продавца')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('sell_currency', models.IntegerField(verbose_name='ID продаваемой крипты')),
                ('buy_currency', models.IntegerField(verbose_name='ID покупаемой крипты')),
                ('sell_quantity', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Сумма продаваемой крипты')),
                ('buy_quantity', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Сумма покупаемой крипты')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('participant', models.CharField(blank=True, max_length=150, verbose_name='Email покупателя')),
                ('status', models.CharField(max_length=30, verbose_name='Статус сделки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефонный номер')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
            ],
            options={
                'db_table': 'et_trade',
            },
        ),
        migrations.DeleteModel(
            name='TradeCash',
        ),
        migrations.DeleteModel(
            name='TradeCript',
        ),
    ]
