# Generated by Django 3.2.9 on 2021-11-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_auto_20211110_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='type',
            field=models.CharField(choices=[('1', 'Trade With cript'), ('2', 'Trade with cash'), ('3', 'Trade with card')], default='1', max_length=10, verbose_name='Тип сделки'),
            preserve_default=False,
        ),
    ]
