# Generated by Django 3.2.9 on 2021-11-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_alter_trade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='bank_card',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
