# Generated by Django 3.2.9 on 2021-11-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_auto_20211110_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('1', 'in anticipation'), ('2', 'in processing'), ('3', 'finished')], default='1', max_length=30, verbose_name='Статус сделки'),
        ),
    ]
