# Generated by Django 3.2.9 on 2021-11-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_alter_trade_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='owner_confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='participant_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
