# Generated by Django 3.2.9 on 2021-11-11 10:02

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_auto_20211111_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buy_currency',
            field=models.CharField(max_length=12, verbose_name='Покупаемая крипта'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buy_quantity',
            field=models.CharField(max_length=32, verbose_name='Сумма покупаемой крипты'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='create_at',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='latitude',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='longitude',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell_currency',
            field=models.CharField(max_length=12, verbose_name='Продаваемая крипта'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell_quantity',
            field=models.CharField(max_length=32, verbose_name='Сумма продаваемой крипты'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='updated_at',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True),
        ),
    ]
