# Generated by Django 3.2.9 on 2021-11-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_auto_20211111_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('expectation', 'expectation'), ('process', 'in processing'), ('finished', 'finished')], default='expectation', max_length=30, verbose_name='Статус сделки'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='type',
            field=models.CharField(choices=[('cript', 'Trade With cript'), ('cash', 'Trade with cash'), ('card', 'Trade with card')], max_length=10, verbose_name='Тип сделки'),
        ),
    ]
