# Generated by Django 3.2.9 on 2021-11-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_auto_20211111_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='sell_quantity_with_commission',
            field=models.CharField(default=1, max_length=12, verbose_name='Сумма продажи с учетом комиссии'),
            preserve_default=False,
        ),
    ]
