# Generated by Django 3.2.9 on 2021-11-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_trade_sell_quantity_with_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='is_active',
        ),
        migrations.AddField(
            model_name='trade',
            name='owner_operation',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='participant_operation',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
