# Generated by Django 3.2.9 on 2021-11-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_auto_20211118_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='create_at',
            field=models.CharField(blank=True, default=1637575847.451923, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='owner_operation',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='participant_operation',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='updated_at',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
