# Generated by Django 3.2.9 on 2021-11-16 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaltransfer',
            name='security_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('\\d{6,10}', code='invalid_code', message='Пароль должен быть менее 10 символов и больше 6 символов и содержать только цифры')]),
        ),
    ]
