# Generated by Django 3.2.9 on 2021-11-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_transfer', '0002_alter_internaltransfer_security_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaltransfer',
            name='owner_operation',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='recipient_operation',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
