# Generated by Django 3.2.9 on 2021-11-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_transfer', '0003_auto_20211118_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaltransfer',
            name='create_at',
            field=models.CharField(blank=True, default=1637575847.464948, max_length=64, null=True),
        ),
        migrations.AlterModelTable(
            name='internaltransfer',
            table='et_internal_transfer',
        ),
    ]
